const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-background py-8">
      <div className="container mx-auto px-4 max-w-4xl">
        <h1 className="text-4xl font-bold mb-8">Terms and Conditions</h1>
        <p className="text-muted-foreground mb-8">Last updated: January 2024</p>

        <div className="space-y-6 prose prose-slate max-w-none">
          <div className="bg-muted/50 p-4 rounded-lg mb-6">
            <p className="text-sm text-muted-foreground font-medium">
              THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION TECHNOLOGY ACT, 2000 ("IT ACT") AND RULES ISSUED THEREUNDER, AS APPLICABLE AND THE PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE IT ACT AND IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF APPLICABLE LAWS, INCLUDING THE CONSUMER PROTECTION (E-COMMERCE) RULES 2020, THAT REQUIRE PUBLISHING THE RULES AND REGULATIONS, PRIVACY POLICY AND TERMS AND CONDITIONS FOR ACCESS OR USAGE OF THE WEBSITE. THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
            </p>
          </div>

          <section>
            <p className="text-muted-foreground mb-4">
              PLEASE READ THESE TERMS AND CONDITIONS ("T&C") CAREFULLY. BY ACCESSING, BROWSING, USING ShopKart OR ANY OTHER WEBSITE, MOBILE VERSION OF THE WEBSITE OR MOBILE APPLICATION (THE TOGETHER "WEBSITE") OR AVAILING ANY OF THE PRODUCTS OF SHOPKART LIMITED (HEREINAFTER REFERRED TO AS "COMPANY" OR "US" OR "WE") YOU INCLUDING THE PERSONS WHO BROWSES OR THE PERSONS WHO ORDERS THE PRODUCT AGREE TO BE BOUND BY ALL OF THE T&C MENTIONED HEREUNDER.
            </p>
            
            <p className="text-muted-foreground mb-4">
              Only persons who can enter into legally binding contracts under the Indian Contract Act, 1872 can use the Website and/or transact on the Website. Any minor who wishes to use or access the Website is required to conduct such a transaction through their legal guardian or parents. If you represent a company, partnership firm or sole proprietorship, you shall be eligible to access and use the Website to conduct the transactions on its behalf only if you have been duly authorized by way of necessary corporate action, as may be prescribed statutorily and/or under the charter documents of such entity.
            </p>

            <p className="text-muted-foreground mb-4">
              The Company reserves the right to amend or revise the T&C at any time by uploading a revised or amended T&C on the Website with or without prior notice. The amended T&C will be effective immediately after it is uploaded on this Website. Your access or use of the Website following any such changes constitutes your acceptance to follow and You shall be bound by these T&C, as amended. The version of the T&C that will apply to your order will be those uploaded on the Website at the time you use or access or place your order. For this reason, we encourage you to review these T&C each time you access and place your order. This T&C does not alter in any way the terms or conditions of any other written agreement you may have with the Company for other products or services. If you do not agree to this T&C (including any referenced policies or guidelines), please immediately terminate your use of the Website. If you would like to print this T&C, please press CTRL + P.
            </p>

            <p className="text-muted-foreground">
              You may only access the Website for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to your use of the Website.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">PRODUCTS</h2>
            
            <h3 className="text-xl font-semibold mb-3">Terms of Offer</h3>
            <p className="text-muted-foreground mb-4">
              The Website offers for sale certain products ("Products"). The Products shall include trial products and the products offered free of cost. By placing an order for the Products through the Website, you agree to the terms and conditions set forth in this T&C. The Products described on the Website, and any samples thereof we may provide to you, are for personal use only. You may not sell or resell any of the Products, or samples thereof, you receive from us unless agreed otherwise. We reserve the right, with or without notice, to cancel or reduce the quantity of any Products to be provided to you that we believe, in our sole discretion, may result in the violation of our T&C.
            </p>

            <p className="text-muted-foreground mb-4">
              The Company may change, suspend, or discontinue the availability of any of the Products at any time, without any notice or liability. You acknowledge that the price payable in connection with the Product or any service, may be subject to change, without notice or liability.
            </p>

            <p className="text-muted-foreground mb-4">
              While describing our Products on our Website, we endeavor to be as accurate as possible. To the extent implied by applicable law, we do not warrant that the Product descriptions, colors, information or other content available on the Website are accurate, complete, reliable, current, or error-free. The Website may contain typographical errors or inaccuracies and may not be complete or updated. Such errors, inaccuracies or omissions may also relate to pricing and availability of the Product or services. Please note that the Product pictures are indicative and may not match the actual Product.
            </p>

            <h3 className="text-xl font-semibold mb-3">Customer Solicitation</h3>
            <p className="text-muted-foreground mb-4">
              By accessing the Website or placing an order or sending any information, you are communicating with the Company electronically and you agree to receive communications (including transactional, promotional and/or commercial messages) from the Company periodically and as and when required. We may communicate with you by email, SMS, phone call or by posting notices on the Website or by any other mode of communication.
            </p>

            <p className="text-muted-foreground mb-4">
              At any point of time, you have the right to withdraw your consent by following the below stated opt-out procedure.
            </p>

            <h3 className="text-xl font-semibold mb-3">Opt Out Procedure</h3>
            <p className="text-muted-foreground mb-4">We provide 2 easy ways to opt out from future Customer Solicitations:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground mb-4">
              <li>You may use the opt out link found in any email solicitation that you may receive.</li>
              <li>You may also choose to opt out, via sending your email by addressing to: support@shopkart.com</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">Proprietary Rights</h3>
            <p className="text-muted-foreground mb-4">
              All the brand names owned and licensed to the Company are exclusive property of the Company, its affiliates, partners or licensors, and is protected by laws of India, including laws governing all applicable forms of intellectual property. The Company has the proprietary rights and trade secrets in the Products. You shall not copy, reproduce, modify, duplicate, re-publish, re-sell or re-distribute any Product manufactured and/or distributed by the Company in whole or in part or in any other form whatsoever. The Company also has rights to all trademarks and trade dress and specific layouts of this webpage, including without limitation calls to action, text placement, images, technology, content, software and other materials, which appear on the Website, including its looks and feel. No trademark is granted in connection with the Products or the materials contained on the Website. The access to the Website does not authorize anyone to use any trademarks in any manner. The trademarks displayed on the Website whether registered or unregistered, are the intellectual property of the Company.
            </p>

            <h3 className="text-xl font-semibold mb-3">Tax</h3>
            <p className="text-muted-foreground">
              If you purchase any Products, you will be responsible for paying any applicable taxes in relation to such purchase.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">WEBSITE</h2>
            
            <h3 className="text-xl font-semibold mb-3">Your Account</h3>
            <p className="text-muted-foreground mb-4">
              You may create and hold one user account ("Account") only. You will be responsible for maintaining confidentiality of your account, password, and restricting access to your computer, and you hereby accept responsibility for all activities that occur under your Account. You acknowledge that the information you provide, in any manner whatsoever, are not confidential or proprietary and does not infringe any rights of a third party in whatsoever nature. Each Account is non-transferrable and may not be sold, traded, combined, or otherwise shared with any other person.
            </p>

            <p className="text-muted-foreground mb-4">
              If you are accessing, browsing and using the Website on someone else's behalf; you represent that you have the authority to bind that person to all the T&C herein. In the event that the person refuses to be bound as the principal to the T&C, you agree to accept liability for any harm caused by any wrongful use of the Website resulting from such access or use of the Website in whatsoever nature.
            </p>

            <p className="text-muted-foreground mb-4">
              If you know or have reasons to believe that the security of your Account has been breached, you should contact us immediately at the 'Contact Information' provided below. If we have found a breach or suspected breach of the security of your Account, we may require you to change your password, temporarily or permanently block or suspend your account without any liability to the Company.
            </p>

            <p className="text-muted-foreground mb-4">
              We reserve the right to refuse service and/or terminate accounts without prior notice if the T&C are violated or if we decide, in our sole discretion, that it would be in the Company's best interests to do so. You are solely responsible for all contents that you upload, post, email or otherwise transmit via the Website. The information provided to us shall be maintained by us in accordance with our Privacy Policy.
            </p>

            <h3 className="text-xl font-semibold mb-3">Payment Method</h3>
            <p className="text-muted-foreground mb-4">The Payments for the Products available on the Website may be made in the following ways:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground mb-4">
              <li>Payments can be made by Credit Cards, Debit Cards, Net Banking, Wallets, UPI, QR, PayPal and reward points.</li>
              <li>Cash on Delivery.</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3">Pricing and Availability</h3>
            <p className="text-muted-foreground mb-4">
              The Prices and availability of the Products, offers and services provided or offered on the Website are subject to change without prior notice and at the sole discretion of the Company. The prices displayed at the Website are inclusive of goods and sales tax ("GST"), but do not include a delivery charge. For all orders under INR 499 (Indian Rupees Four Hundred and Ninety-Nine only), delivery charge shall be levied based on the location of consumer. All orders above INR 499 (Indian Rupees Four Hundred and Ninety-Nine only) shall be delivered without any delivery charges. The Prices and offers in offline store and online on websites and portals other than the Website may vary from the prices displayed on the Website.
            </p>

            <h3 className="text-xl font-semibold mb-3">Delivery</h3>
            <p className="text-muted-foreground mb-4">
              For orders containing multiple Products, delivery may be made in multiple shipments. Delivery usually takes 7-10 business days from the date of order placement. Upon placement of the order, the estimated shipping and delivery timelines shall be available on the order details page. The estimated delivery times are indicative, hence there may be some unforeseeable delays, which are beyond our control. In the event, the Company is unable to deliver the Product within the estimated delivery date due to any reason, you will be notified by an e-mail the reason for such delay. You will have the right either to cancel the ordered Product or wait for the Product to be delivered. Please note that your order will be canceled due to: (i) unavailability of the Product ordered; or (ii) at your instructions, in the event of failure to deliver the Product on the expected time of delivery by our delivery partners. You agree that the Company shall not be liable to pay for any damage or loss either direct or indirect owing to such cancellation of the order or delay in delivery.
            </p>

            <h3 className="text-xl font-semibold mb-3">Tracking Facility</h3>
            <p className="text-muted-foreground">
              Upon dispatch of the Product, you will receive an email or text with the details of the tracking number and the courier company. Orders may also be tracked, by clicking the 'Your orders' option on your My Accounts page. The order status can be tracked after 24 hours from the time of dispatch.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">DISCLAIMER OF WARRANTIES</h2>
            <p className="text-muted-foreground mb-4">
              Your use of the Website and/or Products are at your sole risk. The Website and the Products are offered on an "as is" and "as available" basis. The Company expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose and non-infringement with respect to the Products or Website content, or any reliance upon or use of the Website content or Products.
            </p>

            <p className="text-muted-foreground mb-4">Without limiting the generality of the foregoing, the Company makes no warranty:</p>
            <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
              <li>that the information provided on this Website is accurate, reliable, complete, or timely;</li>
              <li>that the links to third-party websites are to information that is accurate, reliable, complete, or timely;</li>
              <li>no advice or information, whether oral or written, obtained by you from this Website will create any warranty not expressly stated herein;</li>
              <li>as to the results that may be obtained from the use of the Products or that defects in the Products will be corrected; and</li>
              <li>regarding any Products purchased or obtained through the Website.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">LIMITATION OF LIABILITY</h2>
            <p className="text-muted-foreground mb-4">
              The Company takes no liability or exclusive remedy, in law, in equity, or otherwise, with respect to the Website content and Products and/or for any breach of this T&C. The Company will not be liable for any direct, indirect, incidental, special or consequential damages or loss in connection with this T&C or the Products in any manner, including liabilities resulting from (a) the use or the inability to use the Website content or Products or allied services; (b) the cost of procuring substitute the Products or content; (c) any Products purchased or obtained or transactions entered into through the Website; or (d) any lost profits you allege, even if we have been advised of the possibility of such damages and in no event shall our maximum aggregate liability exceed.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">INDEMNIFICATION</h2>
            <p className="text-muted-foreground">
              You will release, indemnify, defend and hold harmless the Company, and any of its contractors, agents, employees, officers, directors, shareholders, affiliates and assigns from all liabilities, claims, damages, costs and expenses, including reasonable attorney's fees and expenses, of third parties relating to or arising out of: (a) this T&C or the breach of your warranties, representations and obligations under this T&C; (b) the Website content or your use of the Website content; (c) the Products or your use of the Products (including trial products); (d) any intellectual property or other proprietary right of any person or entity; (e) your violation of any provision of this T&C; or (f) any information or data you supplied to the Company.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4">GENERAL</h2>
            
            <h3 className="text-xl font-semibold mb-3">Governing Law and Jurisdiction</h3>
            <p className="text-muted-foreground mb-4">
              This T&C shall be construed in accordance with the applicable laws of India and will be governed by the laws of the state of Delhi without regard to its conflict of law principles to the contrary. Neither you nor the Company will commence or prosecute any suit, proceeding or claim to enforce the provisions of this T&C, to recover damages for breach of or default of this T&C, or otherwise arising under or by reason of this T&C, other than in courts located in the State of Delhi.
            </p>

            <h3 className="text-xl font-semibold mb-3">Contact Us</h3>
            <p className="text-muted-foreground mb-2">Customer Service Desk:</p>
            <p className="text-muted-foreground mb-2">Email: support@shopkart.com</p>
            <p className="text-muted-foreground">Contact Days: Monday-Friday (From 9:00 AM to 6:00 PM)</p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;